#!/usr/bin/env bash
# disk.sh — Disk selection, partitioning, formatting, mounting

# Exported variables: INSTALL_DISK, UEFI, EFI_PART, SWAP_PART, ROOT_PART

# Returns the partition path, accounting for nvme/mmcblk naming
_part() {
    local disk="$1" num="$2"
    if [[ "$disk" =~ (nvme|mmcblk) ]]; then
        echo "${disk}p${num}"
    else
        echo "${disk}${num}"
    fi
}

_detect_uefi() {
    if [[ -d /sys/firmware/efi ]]; then
        UEFI="true"
    else
        UEFI="false"
    fi
    export UEFI
}

list_disks() {
    echo -e "\nAvailable disks:"
    lsblk -dpno NAME,SIZE,MODEL | grep -v "loop\|rom" | \
        awk '{printf "  %-16s %s  %s\n", $1, $2, $3}'
    echo
}

select_disk() {
    _detect_uefi

    while true; do
        list_disks
        read -rp "Enter disk to install to (e.g. /dev/sda or /dev/nvme0n1): " INSTALL_DISK
        if [[ -b "$INSTALL_DISK" ]]; then
            break
        fi
        log_warn "\"$INSTALL_DISK\" is not a valid block device, try again."
    done
    export INSTALL_DISK
}

_swap_size_gb() {
    local ram_kb ram_gb swap_gb
    ram_kb=$(awk '/MemTotal/{print $2}' /proc/meminfo)
    ram_gb=$(( (ram_kb + 1048575) / 1048576 ))
    swap_gb=$(( ram_gb > 8 ? 8 : ram_gb ))
    echo "$swap_gb"
}

partition_disk() {
    local disk="$1"
    local swap_gb
    swap_gb=$(_swap_size_gb)

    log_info "Partitioning ${disk} (swap: ${swap_gb}GB, mode: $( [[ "$UEFI" == "true" ]] && echo UEFI/GPT || echo BIOS/MBR ))..."

    # Wipe existing partition table
    wipefs -af "$disk"
    sgdisk -Z "$disk" &>/dev/null || true

    if [[ "$UEFI" == "true" ]]; then
        # GPT layout: EFI | SWAP | ROOT
        parted -s "$disk" \
            mklabel gpt \
            mkpart ESP fat32 1MiB 513MiB \
            set 1 esp on \
            mkpart primary linux-swap 513MiB "$((513 + swap_gb * 1024))MiB" \
            mkpart primary ext4 "$((513 + swap_gb * 1024))MiB" 100%

        EFI_PART="$(_part "$disk" 1)"
        SWAP_PART="$(_part "$disk" 2)"
        ROOT_PART="$(_part "$disk" 3)"
    else
        # MBR layout: SWAP | ROOT (ROOT is bootable)
        parted -s "$disk" \
            mklabel msdos \
            mkpart primary linux-swap 1MiB "${swap_gb}GiB" \
            mkpart primary ext4 "${swap_gb}GiB" 100% \
            set 2 boot on

        SWAP_PART="$(_part "$disk" 1)"
        ROOT_PART="$(_part "$disk" 2)"
        EFI_PART=""
    fi

    export EFI_PART SWAP_PART ROOT_PART
    partprobe "$disk"
    sleep 1
    log_success "Partitioning done"
}

format_partitions() {
    log_info "Formatting partitions..."

    [[ -n "$EFI_PART" ]]  && mkfs.fat -F32 -n EFI  "$EFI_PART"
    mkswap -L SWAP "$SWAP_PART"
    mkfs.ext4 -L ROOT -F "$ROOT_PART"

    log_success "Formatting done"
}

mount_partitions() {
    log_info "Mounting partitions..."

    local mount_opts="defaults,noatime"
    [[ "$DISK_TYPE" == "ssd" ]] && mount_opts="${mount_opts},discard"

    mount -o "$mount_opts" "$ROOT_PART" /mnt

    if [[ -n "$EFI_PART" ]]; then
        mkdir -p /mnt/boot/efi
        mount "$EFI_PART" /mnt/boot/efi
    fi

    swapon "$SWAP_PART"

    log_success "Partitions mounted"
}

generate_fstab() {
    log_info "Generating /etc/fstab..."
    mkdir -p /mnt/etc

    local root_uuid swap_uuid mount_opts
    root_uuid=$(blkid -s UUID -o value "$ROOT_PART")
    swap_uuid=$(blkid -s UUID -o value "$SWAP_PART")

    mount_opts="defaults,noatime"
    [[ "$DISK_TYPE" == "ssd" ]] && mount_opts="${mount_opts},discard"

    {
        echo "# /etc/fstab — generated by void-installer"
        echo "UUID=$root_uuid  /         ext4  ${mount_opts}  0 1"
        echo "UUID=$swap_uuid  none      swap  sw             0 0"
        if [[ -n "$EFI_PART" ]]; then
            local efi_uuid
            efi_uuid=$(blkid -s UUID -o value "$EFI_PART")
            echo "UUID=$efi_uuid   /boot/efi vfat  defaults       0 2"
        fi
    } > /mnt/etc/fstab

    log_success "/etc/fstab written"
}
